Hotel site/Models/ErrorViewModel.cs
namespace Hotel.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Hotel site/Models/Property.cs
namespace Hotel.Models
{
    public class Property
    {
        public Property(string location, string propname, string price, string pic, string group, string popularity)
        {
            Location = location;
            Propname = propname;
            Price = price;
            Pic = pic;
            Group = group;
            this.popularity = popularity;
        }

        public string  Location { get; set; }
        public string  Propname { get; set; }
        public string Price { get; set; }
        public string Pic { get; set; }
        public string Group { get; set; }
        public string popularity { get; set; }
    }
}

Hotel site/Controllers/HomeController.cs
using Hotel.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Hotel.Controllers;
namespace Hotel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var Allproperties = ReadPropertiesFromFile("Database.txt");
            var mostpicks = Allproperties.Where(property => property.Group == "Most Picks").ToList();
            ViewData["Most"] = mostpicks;

            //var Allproperties = ReadPropertiesFromFile("Database.txt");
            var housewithbeautifulbackyard = Allproperties.Where(property => property.Group == "Houses With Beautiful Backyard").ToList();
            ViewData["BeautifulBackyard"] = housewithbeautifulbackyard;

            var Largelivingroom = Allproperties.Where(property => property.Group == "Hotels With Large Living Rooms").ToList();
            ViewData["LargeRoom"] = Largelivingroom;

            var Kitchenset = Allproperties.Where(property => property.Group == "Apartments With Kitchen Set").ToList();
            ViewData["Kitchen"] = Kitchenset;


            return View();
        }
        public IActionResult Browseby()
        {
            return View();
        }
        public IActionResult Stories()
        {
            return View();
        }
        public IActionResult Agents()
        {
            return View();
        }









        public static List<Property> ReadPropertiesFromFile(string filePath)
        {
            List<Property> properties = new List<Property>();

            using (StreamReader reader = new StreamReader(filePath))
            {
                string line;
                while ((line = reader.ReadLine()) != null)
                {
                    if (!string.IsNullOrWhiteSpace(line))
                    {
                        string[] fields = line.Split('|');

                        if (fields.Length >= 6)
                        {
                            string Location = fields[1].Trim();
                            string Propname = fields[2].Trim();
                            string Price = fields[3].Trim();
                            string Pic = fields[4].Trim();
                            string Group = fields[5].Trim();
                           
                            string popularity = fields[6].Trim();

                            Property property = new Property(Location,Propname,Price,Pic,Group, popularity);
                            properties.Add(property);
                        }
                    }
                }
            }

            return properties;
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
            public IActionResult Error()
            {
                return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            }
        }
   
    }  

Hotel site/Controllers/LogInController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Controllers
{
    public class LogInController : Controller
    {
        public IActionResult LogIn()
        {
            return View();
        }
    }
}

Hotel site/Controllers/SignUpController.cs
using Microsoft.AspNetCore.Mvc;

namespace Hotel.Controllers
{
    public class SignUpController : Controller
    {
        public IActionResult SignUp()
        {
            return View();
        }
    }
}

Hotel site/Views/Home/Agents.cshtml
@{
    ViewData["Title"] = "Agents";
}

<h1>Agents</h1>

Hotel site/Views/Home/Browseby.cshtml
@{
    ViewData["Title"] = "Browseby";
}

<h1>Browseby</h1>

Hotel site/Views/Home/Stories.cshtml
@{
    ViewData["Title"] = "Stories";
}

<h1>Stories</h1>

Hotel site/Views/LogIn/LogIn.cshtml
<!-- Section: Design Block -->
<section class=" text-center text-lg-start">
  
  
  <div class="card mb-3">
    <div class="row g-0 d-flex align-items-center">
      <div class="col-lg-4 d-none d-lg-flex">
        <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" alt="Trendy Pants and Shoes"
          class="w-100 rounded-t-5 rounded-tr-lg-0 rounded-bl-lg-5" />
      </div>
      <div class="col-lg-8">
        <div class="card-body py-5 px-md-5">

          <form>
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="email" id="form2Example1" class="form-control" />
              <label class="form-label" for="form2Example1">Email address</label>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
              <input type="password" id="form2Example2" class="form-control" />
              <label class="form-label" for="form2Example2">Password</label>
            </div>

            <!-- 2 column grid layout for inline styling -->
            <div class="row mb-4">
              <div class="col d-flex justify-content-center">
                <!-- Checkbox -->
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
                  <label class="form-check-label" for="form2Example31"> Remember me </label>
                </div>
              </div>

              <div class="col">
                <!-- Simple link -->
                <a href="#!">Forgot password?</a>
              </div>
            </div>

            <!-- Submit button -->
            <button type="button" class="btn btn-primary btn-block mb-4">Sign in</button>

          </form>

        </div>
      </div>
    </div>
  </div>
</section>
<!-- Section: Design Block -->

Hotel site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>@ViewData["Title"] - Staycation</title> 
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/img/favicon.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/lib/vendor/aos/aos.css" rel="stylesheet">
    <link href="~/lib/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/lib/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/lib/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/lib/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/lib/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />

 
</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center">
        <div class="container d-flex justify-content-between">

            <div >
                <h1 ><a href="index.html"><span style = "color:blue">Stay</span><span style="color:rgb(0,0,20)">cation</span> </a></h1>
                <!-- Uncomment below if you prefer to use an image logo -->
                <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
            </div>

            <nav id="navbar" class="navbar">
                <ul>
                    <li><a class="nav-link scrollto" asp-controller="Home" asp-action="Index" style="color:blue">Home</a></li>
                    <li><a class="nav-link scrollto" asp-controller="Home" asp-action ="BrowseBy">Browse By</a></li>
                    <li><a class="nav-link scrollto" asp-controller="Home"asp-action="Stories">Stories</a></li>
                    <li><a class="nav-link scrollto" asp-controller="Home"asp-action="Agent">Agents</a></li>
                    <li><a class="nav-link scrollto" asp-controller="LogIn" asp-action="LogIn">Log In</a></li>
                    <li><a class="nav-link scrollto" asp-controller="SignUp"asp-action="Signup">Sign Up</a></li>
                </ul>
                <i class="bi bi-list mobile-nav-toggle"></i>
            </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->

 
    <main id="main">

        @RenderBody()
       

    </main><!-- End #main -->
    <!-- ======= Footer ======= -->
    <footer id="footer">
        <div class="footer-top">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-md-6">
                        <div class="footer-info">
                            <div>
                                <h1><a href="index.html"><span style="color:blue">Stay</span><span style="color:rgb(0,0,20)">cation</span> </a></h1>
                           
                            </div>
                            <p>
                                We make your Holiday<br />
                                Memorable and beautiful<br /> 
                            </p>
                            
                        </div>
                    </div>

                    <div class="col-lg-2 col-md-6 footer-links">
                        <h4>For Beginners</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">New Account</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Start Booking a Room</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Use Payments</a></li>
                            
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Explore Us</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#"> Our careers</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Terms and Conditions</a></li>
                             
                        </ul>
                    </div>

                    <div class="col-lg-3 col-md-6 footer-links">
                        <h4>Connect with us</h4>
                        <ul>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Support@staycation.id</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">+234-9045-491-1484</a></li>
                            <li><i class="bx bx-chevron-right"></i> <a href="#">Staycation, Jemang, Jakarta.</a></li>

                        </ul>
                    </div>

                     

                </div>
            </div>
        </div>

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>2023</span></strong>. All rights Reserved. Staycation.
            </div>
            <div class="credits">
                
                Designed by <a href="https://theo-neku.netlify.app/">Oche Isaac</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/lib/vendor/aos/aos.js"></script>
    <script src="~/lib/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/lib/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="~/lib/vendor/swiper/swiper-bundle.min.js"></script>
     

    <!-- Template Main JS File -->
    <script src="~/js/main.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>

Hotel site/Views/SignUp/SignUp.cshtml
<!-- Section: Design Block -->
<section class="text-center text-lg-start">

  <!-- Jumbotron -->
  <div class="container py-4">
    <div class="row g-0 align-items-center">
      <div class="col-lg-6 mb-5 mb-lg-0">
        <div class="card cascading-right" style="
            background: hsla(0, 0%, 100%, 0.55);
            backdrop-filter: blur(30px);
            ">
          <div class="card-body p-5 shadow-5 text-center">
            <h2 class="fw-bold mb-5">Sign up now</h2>
            <form>
              <!-- 2 column grid layout with text inputs for the first and last names -->
              <div class="row">
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <input type="text" id="form3Example1" class="form-control" />
                    <label class="form-label" for="form3Example1">First name</label>
                  </div>
                </div>
                <div class="col-md-6 mb-4">
                  <div class="form-outline">
                    <input type="text" id="form3Example2" class="form-control" />
                    <label class="form-label" for="form3Example2">Last name</label>
                  </div>
                </div>
              </div>

              <!-- Email input -->
              <div class="form-outline mb-4">
                <input type="email" id="form3Example3" class="form-control" />
                <label class="form-label" for="form3Example3">Email address</label>
              </div>

              <!-- Password input -->
              <div class="form-outline mb-4">
                <input type="password" id="form3Example4" class="form-control" />
                <label class="form-label" for="form3Example4">Password</label>
              </div>

              <!-- Checkbox -->
              <div class="form-check d-flex justify-content-center mb-4">
                <input class="form-check-input me-2" type="checkbox" value="" id="form2Example33" checked />
                <label class="form-check-label" for="form2Example33">
                  Subscribe to our newsletter
                </label>
              </div>

              <!-- Submit button -->
              <button type="submit" class="btn btn-primary btn-block mb-4">
                Sign up
              </button>

              <!-- Register buttons -->
              <div class="text-center">
                <p>or sign up with:</p>
                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-mdb"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-google"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-twitter"></i>
                </button>

                <button type="button" class="btn btn-link btn-floating mx-1">
                  <i class="fab fa-github"></i>
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>

      <div class="col-lg-6 mb-5 mb-lg-0">
        <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" class="w-100 rounded-4 shadow-4"
          alt="" />
      </div>
    </div>
  </div>
  <!-- Jumbotron -->
</section>
<!-- Section: Design Block -->